title: + Albert
author: Albert Hardy
email: albert@tanutama.com
description: > # this means to ignore newlines until "baseurl:"
  Designer, Improviser and Researcher. Bridging interaction gap between people and technology; Creating new possibilities. 

url: tanutama.com
google_analytics: UA-124394-1
# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

name: Albert
job: designer
location: Singapore
languages: HTML, CSS and Javascript
twitter_username: alberthardy
email_address: albert@tanutama.com
linkedin_username:  alberthardy

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
#- about.md
#- concepts/index.html

article_navigation:
- title: Archive
  url: /fieldnotes/archive/   
- title: Category
  url: /fieldnotes/category/  
- title: Tag
  url: /fieldnotes/tag/   

#https://jekyllrb.com/docs/permalinks/
permalink: "/fieldnotes/:year/:month/:title/"

# excerpt_separator
# http://www.seanbuscay.com/blog/jekyll-teaser-pager-and-read-more/
excerpt_separator: <!--more-->

# Gems
plugins: [jekyll-paginate]
paginate: 5
paginate_path: "/fieldnotes/page:num"

sass:
  sass_dir: _sass
  # style: compressed

# Build Collections
# https://learn.cloudcannon.com/jekyll/introduction-to-jekyll-collections/
collections:
  projects:
    output: true
    permalink: /:collection/:path/

# Front Matter Defaults
defaults:
  - scope:
      path: ""
      type: projects
    values:
      layout: project
  # _posts
  - scope:
      path: "_posts"
      type: posts
    values:
      layout: post

# Build settings
markdown: kramdown
theme: minima
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - Gruntfile.js
  - package.json
  - package-lock.json
  - History.markdown
  - README.md
  - CODE_OF_CONDUCT.md
  - screenshot.png
  - minima.gemspec
  - LICENSE.txt
  - script
  - dist
  - dev


